# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    # Use default CircleCI NodeJS Docker image for testing
    docker:
      - image: circleci/node:10.7

    working_directory: ~/repo

    steps:
      # 1. Clone code from GitHub
      - checkout

      # 2. Download and cache dependencies
      #    We're assuming our dependencies are fully defined by "yarn.lock"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # 3. Install dependencies
      - run: yarn install

      # 4. Save dependencies to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Run any tests defined in package.json
      - run: yarn test

      # Build Gastby site
      - run: yarn build
